### ISSUE TITLE
reporting error in AssemblyScript build

### ISSUE THREAD

**Issue by jlwaugh** [near-examples/NFT#137]
_via km1tz on Discord_

"The issue is that build script is targeting non existent file (compile.js:18-36)"

### Error Message

```
node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'out/ts-as.wasm'
    at Object.statSync (node:fs:1132:3)
    at reportFilesize (H:\Programming\NEAR Protocol\NFT-example\contracts\assemblyscript\compile.js:55:20)
    at compileContract (H:\Programming\NEAR Protocol\NFT-example\contracts\assemblyscript\compile.js:38:3)
    at Array.map (<anonymous>)
    at Object.<anonymous> (H:\Programming\NEAR Protocol\NFT-example\contracts\assemblyscript\compile.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'out/ts-as.wasm'
}
```

### Replicated Locally

```
yarn build:as
yarn run v1.22.5
$ node ./contracts/assemblyscript/compile.js

compiling contract [ nep4-basic/main.ts ] to [ out/nep4-basic-as.wasm ]
 asconfig.js is deprecated use `asb`to build files.  NOTE: output now in ./build/release/ 
asc /Users/jlwaugh/Desktop/NFT/contracts/assemblyscript/nep4-basic/main.ts -O3z --debug --validate --measure --runPasses inlining-optimizing,dce --optimizeLevel 3 --shrinkLevel 3 --target release --binaryFile build/release/main.wasm
WARNING Unknown option '--validate'
I/O Read   :    13.880 ms  n=320
I/O Write  :     3.245 ms  n=1
Parse      :   918.623 ms  n=133
Initialize :    40.810 ms  n=1
Compile    :   327.185 ms  n=1
Emit       :   139.840 ms  n=1
Validate   :   130.952 ms  n=1
Optimize   :  8465.619 ms  n=1
Transform  :          n/a  n=0
internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, stat 'out/nep4-basic-as.wasm'
    at Object.statSync (fs.js:1016:3)
    at reportFilesize (/Users/jlwaugh/Desktop/NFT/contracts/assemblyscript/compile.js:55:20)
    at compileContract (/Users/jlwaugh/Desktop/NFT/contracts/assemblyscript/compile.js:38:3)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/jlwaugh/Desktop/NFT/contracts/assemblyscript/compile.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'out/nep4-basic-as.wasm'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bucanero** [comment]
AssemblyScript contract has been deprecated.
